server.port=9091

spring.cloud.gateway.discovery.locator.enabled=false

spring.cloud.gateway.routes[0].id=USERSERVICE
spring.cloud.gateway.routes[0].uri=lb://USERSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=ORDERSERVICE
spring.cloud.gateway.routes[1].uri=lb://ORDERSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
